### ISSUE TITLE
bug: TypeError: must be str, not bytes in tool ConstructAccess.py

### ISSUE THREAD

**Issue by gluckzhang** [gluckzhang/k8s-brochure#3]
Hi @Tailp , when I tested the following command `python ConstructAccess.py createEx -n repairnator -a user tailp`, I got an error. Could you take a look at this :)

```
$ python ConstructAccess.py createEx -n repairnator -a user tailp

b'serviceaccount/tailp created\nrole.rbac.authorization.k8s.io/tailp-user created\nrolebinding.rbac.authorization.k8s.io/tailp created\n'
Traceback (most recent call last):
  File "ConstructAccess.py", line 326, in <module>
    cases[sys.argv[1]]()
  File "ConstructAccess.py", line 228, in case3
    generate_new_config(namespace_name,elem,sys.argv[1],access_kind)
  File "ConstructAccess.py", line 161, in generate_new_config
    create_config(namespace_name,namespace_username)
  File "ConstructAccess.py", line 84, in create_config
    cmd_token = "kubectl get secret " + secret_name[1:len(secret_name)-1] + " -n " + namespace_name +" -o 'jsonpath={.data.token}' | base64 -d"
TypeError: must be str, not bytes
```

**Comment by henry-lp** [comment]
Hi @gluckzhang , I think maybe we have different configuration or something. Do you mind meeting up so that I can directly debug in your enviroment :) ? . Here is my output and it seems like everything works fine. I am already at my office maybe btw, so we can take this together with the other issue :).

![Screenshot from 2019-06-14 13-11-44](https://user-images.githubusercontent.com/33935517/59505583-1a643180-8ea6-11e9-9276-ffadfe979cab.png)

**Comment by gluckzhang** [comment]
@Tailp , yes, should be a Python environment issue. We will fix it this afternoon.

**Comment by gluckzhang** [comment]
The correct working Python should be Python2, fixed.
